pre-commit:
  jobs:
    - name: lint frontend
      run: pnpm exec biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files} && git add {staged_files}
      stage_fixed: true

commit-msg:
  jobs:
    - name: lint-commit-message
      run: pnpm exec commitlint --edit {1}

pre-push:
  commands:
    type-check-frontend:
      files: git diff --name-only origin/master...HEAD
      glob: "frontend/**/*"
      run: pnpm --filter frontend run type-check && pnpm --filter frontend run lint-check

    type-check-backend:
      files: git diff --name-only origin/master...HEAD
      glob: "backend/**/*"
      run: pnpm --filter backend run type-check && pnpm --filter backend run lint-check

    tests-frontend:
      files: git diff --name-only origin/master...HEAD
      glob: "frontend/src/**/*"
      run: pnpm run test:frontend

    tests-backend:
      files: git diff --name-only origin/master...HEAD
      glob: "backend/src/**/*"
      run: pnpm run test:backend
