pre-commit:
  parallel: true
  commands:
    biome-check:
      run: pnpm exec biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
      stage_fixed: true


commit-msg:
  commands:
    lint-commit-message:
      run: pnpm exec commitlint --edit {1}


pre-push:
  parallel: false
  commands:
    biome-check:
      run: pnpm exec biome check --no-errors-on-unmatched --files-ignore-unknown=true {push_files} || echo "skipped"

    type-check-fe:
      run: grep "^frontend/" > /dev/null && pnpm --filter frontend exec tsc --noEmit || echo "skipped"
    type-check-be:
      run: grep "^backend/" > /dev/null && pnpm --filter backend exec tsc --noEmit || echo "skipped"

    tests-fe:
      run: grep "^frontend/" > /dev/null && pnpm --filter frontend exec vitest run || echo "skipped"
    tests-be:
      run: grep "^backend/" > /dev/null && pnpm --filter backend exec vitest run || echo "skipped"
