pre-commit:
  parallel: true
  commands:
    biome-check:
      run: pnpm exec biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
      stage_fixed: true

commit-msg:
  commands:
    lint-commit-message:
      run: pnpm exec commitlint --edit {1}

pre-push:
  parallel: false
  commands:
    biome-check:
      run: |
        pnpm exec biome check --no-errors-on-unmatched --files-ignore-unknown=true "./frontend/src/**/*.{ts,tsx,json,css} !frontend/src/**/*.gen.ts" || echo "⚠️ frontend biome-check skipped"
        pnpm exec biome check --no-errors-on-unmatched --files-ignore-unknown=true "./backend/src/**/*.{ts,json}" || echo "⚠️ backend biome-check skipped"

    type-check:
      run: |
        pnpm --filter frontend exec tsc --noEmit || echo "⚠️ frontend type-check skipped"
        pnpm --filter backend exec tsc --noEmit || echo "⚠️ backend type-check skipped"

    tests:
      run: |
        pnpm --filter frontend exec vitest run || echo "⚠️ frontend tests skipped"
        pnpm --filter backend exec vitest run || echo "⚠️ backend tests skipped"

