#version: '3.8'

#  backend:
#    build: ./backend
#    restart: always
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./backend:/app
#      - /app/node_modules
#    depends_on:
#      - postgres
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: mypass
#      DB_NAME: appdb

#volumes:
#  pgdata:
